# Generated by Django 2.0 on 2019-02-19 22:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20190206_1805'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='videourl',
            managers=[
                ('urlobj', django.db.models.manager.Manager()),
            ],
        ),
    ]
